---
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
before_install: gem install bundler -v 2.1.4

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
